# configuration.yml

# configuration for the instrument package
# simple key:value pairs

ADSIM_IOC_PREFIX: "9idDetectorSim:"
ADPILATUS_IOC_PREFIX: "PILATUS_1MF:"
ADLAMBDA_IOC_PREFIX: "8LAMBDA1:"
GP_IOC_PREFIX: "8idChmLab:"

DATABROKER_CATALOG: &databroker_catalog GIXStb

# default RunEngine metadata
RUNENGINE_METADATA:
  beamline_id: GIXStb
  instrument_name: APS GIXS Testbed
  proposal_id: commissioning
  databroker_catalog: *databroker_catalog

# paths
# AD_IMAGE_DIR: "adsimdet/%Y/%m/%d"
# AD_MOUNT_PATH: /tmp
# BLUESKY_MOUNT_PATH: /tmp/docker_ioc/iocad/tmp

# permissions
ALLOW_AREA_DETECTOR_WARMUP: false
ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: true
ENABLE_CALCS: true
USE_PROGRESS_BAR: false
WRITE_SPEC_DATA_FILES: true

# override default control layer for ophyd
# if undefined, defaults to PyEpics
# OPHYD_CONTROL_LAYER: PyEpics
# OPHYD_CONTROL_LAYER: caproto

# ----------------------------------

# default timeouts (seconds)
PV_READ_TIMEOUT: &TIMEOUT 60
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: *TIMEOUT

XMODE_DEBUG_LEVEL: Minimal

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 8
MINIMUM_BLUESKY_VERSION:
  - 1
  - 10
MINIMUM_OPHYD_VERSION:
  - 1
  - 7
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
