# configuration.yml

# configuration for the instrument package
# simple key:value pairs

ADSIM_IOC_PREFIX: "9idDetectorSim:"
ADPILATUS_IOC_PREFIX: "PILATUS_1MF:"
ADLAMBDA_IOC_PREFIX: "8LAMBDA1:"
GP_IOC_PREFIX: "8idChmLab:"

DATABROKER_CATALOG: &databroker_catalog CSSItb

# default RunEngine metadata
RUNENGINE_METADATA:
  beamline_id: CSSItb
  instrument_name: APS CSSI Testbed
  proposal_id: commissioning
  databroker_catalog: *databroker_catalog

# paths
ADSIM_IMAGE_DIR: "simdet"
ADPILATUS_IMAGE_DIR: "pilatus"
ADLAMBDA_IMAGE_DIR: "lambda"
# AD_IMAGE_DIR: "adsimdet/%Y/%m/%d"
# If your detector IOC sees the same file system as the bluesky workstation, 
# then AD_MOUNT_PATH and BLUESKY_MOUNT_PATH should be the same.
AD_MOUNT_PATH: /net/s8iddata/export/8-id-g/2023-1/bsTests
PILATUS_MOUNT_PATH: /net/s8iddata/8-id-g/2023-1/bsTests
BLUESKY_MOUNT_PATH: /net/s8iddata/export/8-id-g/2023-1/bsTests

# permissions
ALLOW_AREA_DETECTOR_WARMUP: False
ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: True
ENABLE_CALCS: True
USE_PROGRESS_BAR: False
WRITE_SPEC_DATA_FILES: False

# override default control layer for ophyd
# if undefined, defaults to PyEpics
# OPHYD_CONTROL_LAYER: PyEpics
# OPHYD_CONTROL_LAYER: caproto

# ----------------------------------

# default timeouts (seconds)
PV_READ_TIMEOUT: &TIMEOUT 60
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: *TIMEOUT

XMODE_DEBUG_LEVEL: Minimal

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 8
MINIMUM_BLUESKY_VERSION:
  - 1
  - 10
MINIMUM_OPHYD_VERSION:
  - 1
  - 7
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
